# https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

grafana:
  # adminPassword is set manually after install for security
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.pratik-labs.xyz
