# This tells Kubernetes which API version to use for these resource. Deployments live in apps/v1.
apiVersion: apps/v1

#This tells what type of resource I am creating. I am telling Kubernetes "I want a Deployment".
kind: Deployment

#This contains basic information about the resource
metadata:
  name: demo #The name of the Deployment Manager.
  namespace: default # Which namespace to put it in. Like a folder inside the cluster.

# This is where you describe what I actually want
spec:
  replicas: 2 # Crete 2 pods. Run 2 copies of this app. If one crashes, the other keeps serving traffic. Kubernetes automatically restarts the crashed one.
  selector:
    matchLabels: # how the Deployment finds which pods belong to it. It looks for Pods with label app: demo
      app: demo # manage pods that have this label

#The blueprint for each Pod the Deployment creates.
  template: # when creating a pod, use this bluepring
    metadata:
      labels: # gives each Pod the label app:demo so the Deployment can find them via matchLabels
        app: demo
    spec:
      containers: #the actual container to run inside each Port
        - name: demo # container name
          image: nginx:alpine #which Docker image to use. Run this container
          ports:
            - containerPort: 80 # the port the container listens on
