# https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

grafana:
  # adminPassword is set manually after install for security
  persistence:
    enabled: true
    storageClassName: local-path
    size: 5Gi
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.pratik-labs.xyz

prometheus:
  prometheusSpec:
    retention: 30d # Keep metrics history for 30 days
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
alertmanager:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - alertmanager.pratik-labs.xyz
    paths:
      - /
    pathType: Prefix
  config:
    route:
      receiver: 'discord'
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      routes:
        - receiver: 'null'
          matchers:
            - alertname = "Watchdog"
    receivers:
      - name: 'null'
      - name: 'discord'
        discord_configs:
          - webhook_url: 'https://discord.com/api/webhooks/1494726528431427776/cOXapEqpPt2SN--M8oU2oaYNFmXp6_Okvu_D1PDKHtMOkXdn5BwQ-nbydEvCENGpUb3M'
            send_resolved: true
