apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-pv
spec:
  capacity:
    storage: 500Gi
  accessModes: ["ReadWriteOnce"]
  hostPath:
    path: /mnt/storage/Photos
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
  namespace: immich
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  volumeName: immich-library-pv
