apiVersion: v1
kind: Namespace
metadata:
  name: apps

--- # This seperates the multiple resources in one file

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring # For prometheus, grafana, alertmanager

---

apiVersion: v1
kind: Namespace
metadata:
  name: tunnel # For cloudflared tunnel

---

apiVersion: v1
kind: Namespace
metadata:
  name: argocd # For Argo CD GitOps

---

apiVersion: v1
kind: Namespace
metadata:
  name: immich # For immich photo management

---

apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud # For Nextcloud
