- name: Install k3s
  hosts: control_plane
  become: true

  tasks:
    - name: Download and install k3s
      shell: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--tls-san k8s-server.taile34db4.ts.net --tls-san 192.168.1.100" sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for k3s to be ready
      wait_for:
        path: /etc/rancher/k3s/k3s.yaml
        timeout: 60

    - name: Enable and start k3s service
      systemd:
        name: k3s
        enabled: true
        state: started
