- name: Fetch kubeconfig to local machine
  hosts: control_plane
  become: true

  tasks:
    - name: Copy k3s kubeconfig to user home
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/pratikserver/k3s.yaml
        owner: pratikserver
        mode: "0600"
        remote_src: true #by default the Ansible looks for the src file on the local machine. This tells it "no, the source file is already on the remote server, copy it within the server itself."
    - name: Fetch kubeconfig to local machine
      fetch:
        src: /home/pratikserver/k3s.yaml
        dest: ~/.kube/config
        flat: true #in fetch module, by default ansible creates a nested folder structure when downloading like {destination/inventory_hostname/remote_full_path}, here the flat: true ignores all that and save the file directly where the sect specified

    - name: Remove temporary kubeconfig copy from the server
      file:
        path: /home/pratikserver/k3s.yaml
        state: absent
