# https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    hostname: argocd.pratik-labs.xyz

  extraArgs:
    - --insecure

configs:
  params:
    server.insecure: true
