apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-hdd-pv
spec:
  capacity:
    storage: 500Gi
  accessModes: ["ReadWriteOnce"]
  hostPath:
    path: /mnt/storage
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-hdd-pvc
  namespace: nextcloud
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  volumeName: nextcloud-hdd-pv
